---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup}
library(p8105.datasets)
library(tidyverse)
library(plotly)
```

## Loading Data
```{r}
data("ny_noaa")

noaa = ny_noaa %>% 
  mutate(date2 = date) %>% 
  separate(date2, into = c("year", "month", "day"), sep = "-", convert = TRUE) %>% 
  mutate(tmax = as.numeric(tmax)/10, 
         tmin = as.numeric(tmin)/10,
         prcp = prcp/10) %>% 
  sample_n(10000)

#years with top 5 highest temps vs years with top 5 lowest temps

```

## Plotly Plots

### Scatterplot
```{r}
noaa %>% 
  mutate(text_label = str_c("Station ID:", id)) %>% 
  plot_ly(x = ~tmin, y = ~tmax, color = ~year, text = ~text_label, alpha = 0.5, type = "scatter", mode = "markers")
```

### Barplot
```{r}
noaa %>% 
  mutate(text_label2 = str_c("Date:", date, "\nLocation ID:", id)) %>% 
  plot_ly(x = ~year, y = ~snwd, color = ~month, text = ~text_label2, type = "bar") %>% 
  layout(title = 'Snow Depth by Year', 
         xaxis = list(title = 'Year'), 
         yaxis = list(title = 'Snow Depth (mm)'))
```


